# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1150, 686)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inventoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.inventoryLabel.setGeometry(QtCore.QRect(360, 50, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.inventoryLabel.setFont(font)
        self.inventoryLabel.setStyleSheet("color: #2f80ed;")
        self.inventoryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inventoryLabel.setObjectName("inventoryLabel")
        self.actionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.actionBtn.setEnabled(True)
        self.actionBtn.setGeometry(QtCore.QRect(20, 570, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Gurajada")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.actionBtn.setFont(font)
        self.actionBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actionBtn.setStyleSheet("QPushButton {\n"
"background-color: #2f80ed;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(29, 255, 0);\n"
"color: rgba(0, 0, 0, 206);\n"
"}")
        self.actionBtn.setObjectName("actionBtn")
        self.footer = QtWidgets.QLabel(self.centralwidget)
        self.footer.setGeometry(QtCore.QRect(0, 640, 1151, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(12)
        self.footer.setFont(font)
        self.footer.setStyleSheet("color: #2f80ed;")
        self.footer.setAlignment(QtCore.Qt.AlignCenter)
        self.footer.setObjectName("footer")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(100, 150, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: #2f80ed;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.menuLabel = QtWidgets.QLabel(self.centralwidget)
        self.menuLabel.setGeometry(QtCore.QRect(100, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.menuLabel.setFont(font)
        self.menuLabel.setStyleSheet("color: #2f80ed;")
        self.menuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.menuLabel.setObjectName("menuLabel")
        self.inventoryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.inventoryBtn.setGeometry(QtCore.QRect(20, 380, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Gurajada")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.inventoryBtn.setFont(font)
        self.inventoryBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inventoryBtn.setStyleSheet("QPushButton {\n"
"background-color: #2f80ed;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 0, 0, 206);\n"
"color: #2f80ed;\n"
"}")
        self.inventoryBtn.setObjectName("inventoryBtn")
        self.accessibilityBtn = QtWidgets.QPushButton(self.centralwidget)
        self.accessibilityBtn.setGeometry(QtCore.QRect(20, 450, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Gurajada")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.accessibilityBtn.setFont(font)
        self.accessibilityBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accessibilityBtn.setStyleSheet("QPushButton {\n"
"background-color: #2f80ed;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 0, 0, 206);\n"
"color: #2f80ed;\n"
"}")
        self.accessibilityBtn.setObjectName("accessibilityBtn")
        self.commandLine = QtWidgets.QLineEdit(self.centralwidget)
        self.commandLine.setGeometry(QtCore.QRect(10, 210, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.commandLine.setFont(font)
        self.commandLine.setStyleSheet("color: #2f80ed;\n"
"background-color: rgb(60, 60, 60);\n"
"border-radius: 8px;")
        self.commandLine.setText("")
        self.commandLine.setAlignment(QtCore.Qt.AlignCenter)
        self.commandLine.setClearButtonEnabled(True)
        self.commandLine.setObjectName("commandLine")
        self.comboBtn = QtWidgets.QComboBox(self.centralwidget)
        self.comboBtn.setGeometry(QtCore.QRect(20, 510, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBtn.setFont(font)
        self.comboBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBtn.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: #2f80ed;")
        self.comboBtn.setEditable(False)
        self.comboBtn.setCurrentText("")
        self.comboBtn.setMaxVisibleItems(5)
        self.comboBtn.setMinimumContentsLength(1)
        self.comboBtn.setDuplicatesEnabled(False)
        self.comboBtn.setFrame(True)
        self.comboBtn.setObjectName("comboBtn")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(100, -10, 141, 161))
        self.logo.setStyleSheet("image: url(:/logo/images/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.statusBrowser = QtWidgets.QListWidget(self.centralwidget)
        self.statusBrowser.setGeometry(QtCore.QRect(760, 110, 371, 481))
        self.statusBrowser.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border: 2px solid rgb(47, 128, 237);\n"
"color: white;")
        self.statusBrowser.setObjectName("statusBrowser")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(760, 50, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: #2f80ed;")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendBtn.setEnabled(True)
        self.sendBtn.setGeometry(QtCore.QRect(50, 250, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Gurajada")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.sendBtn.setFont(font)
        self.sendBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendBtn.setStyleSheet("QPushButton {\n"
"background-color: #2f80ed;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(29, 255, 0);\n"
"color: rgba(0, 0, 0, 206);\n"
"}")
        self.sendBtn.setObjectName("sendBtn")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setEnabled(True)
        self.clearBtn.setGeometry(QtCore.QRect(760, 590, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Gurajada")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.clearBtn.setFont(font)
        self.clearBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(47, 128, 237);\n"
"border: 2px solid rgb(47, 128, 237);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 0, 0, 206);\n"
"color: #2f80ed;\n"
"}")
        self.clearBtn.setObjectName("clearBtn")
        self.inventoryBrowser = QtWidgets.QTableWidget(self.centralwidget)
        self.inventoryBrowser.setGeometry(QtCore.QRect(360, 110, 381, 511))
        self.inventoryBrowser.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border: 2px solid rgb(47, 128, 237);\n"
"color: white;")
        self.inventoryBrowser.setObjectName("inventoryBrowser")
        self.inventoryBrowser.setColumnCount(0)
        self.inventoryBrowser.setRowCount(0)
        self.logo.raise_()
        self.footer.raise_()
        self.inventoryLabel.raise_()
        self.actionBtn.raise_()
        self.menuLabel.raise_()
        self.title.raise_()
        self.inventoryBtn.raise_()
        self.accessibilityBtn.raise_()
        self.commandLine.raise_()
        self.comboBtn.raise_()
        self.statusBrowser.raise_()
        self.statusLabel.raise_()
        self.sendBtn.raise_()
        self.clearBtn.raise_()
        self.inventoryBrowser.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Octopus - Проект диссертации"))
        self.inventoryLabel.setText(_translate("MainWindow", "Inventory browser"))
        self.actionBtn.setText(_translate("MainWindow", "Action"))
        self.footer.setText(_translate("MainWindow", "created by Vladislav Romanov in 2023"))
        self.title.setText(_translate("MainWindow", "Octopus"))
        self.menuLabel.setText(_translate("MainWindow", "Menu"))
        self.inventoryBtn.setText(_translate("MainWindow", "Inventory"))
        self.accessibilityBtn.setText(_translate("MainWindow", "Accessibility"))
        self.commandLine.setPlaceholderText(_translate("MainWindow", "Command line"))
        self.comboBtn.setPlaceholderText(_translate("MainWindow", "Modules"))
        self.statusLabel.setText(_translate("MainWindow", "Status browser"))
        self.sendBtn.setText(_translate("MainWindow", "Paremeters"))
        self.clearBtn.setText(_translate("MainWindow", "Clear browser"))
import logo
